#!/bin/bash

# Starter script
if [ -n  "${1}" ] && [ ${1} = "update" ]; then
	cd /usr/local/Ganymed && git fetch origin master && git reset --hard origin/master && git pull origin master	
elif [ -n "${1}" ] && [ ${1} != "update" ]; then
	echo "Unknown option ${1}"
else
	cd /usr/local/Ganymed && ruby ganymed.rb 
fi
